sudo: required

language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y -s ppa:nerdboy/embedded
  - sudo apt-get -qq update

# command to install dependencies
install:
  - sudo apt-get -y install zerotier-one
  - sudo apt-get -y build-dep fpnd
  - pip install pytest
  - pip install pytest-pep8
  - pip install pytest-flake8
  - pip install tox-travis

# command to run tests
script:
  - tox

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

notifications:
  irc:
    channels:
      - "irc.freenode.org#code-hell"
      - "irc.freenode.org#allieae"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

